Weddingram/urls.py
from django.contrib import admin
from django.urls import path, include
from Weddingram.views import Index
from content.views import Main, UploadFeed
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', Main.as_view()),
    path('', Index.as_view()),
    path('content/', include('content.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from content import views
from django.urls import path
from .views import UploadFeed, UploadReply



app_name = 'content'
urlpatterns= [
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('account/', views.account, name='account'),
    path('copyright/', views.copyright, name='copyright'),
    path('weddingvows/', views.weddingvows, name='weddingvows'),
    path('location/', views.location, name='location'),
    path('upload', UploadFeed.as_view()),
    path('reply', UploadReply.as_view())
]

content/models.py
from django.db import models

# Create your models here.
class Feed(models.Model):
    content = models.TextField() #글내용
    image = models.TextField() #포스트이미지
    user_id = models.TextField() #작성자아이디
    like_count = models.IntegerField() #라이크카운트
    write_date = models.TextField() #콘텐츠작성일
    tag = models.TextField() #태그


class Reply(models.Model):
    feed_id = models.IntegerField(default=0)
    writer_id = models.TextField()
    comment = models.TextField()

Weddingram/views.py
from django.shortcuts import render
from rest_framework.views import APIView


class Index(APIView):
    def get(self, request):
        return render(request, "Weddingram/index.html")

content/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Feed, Reply
import os
from uuid import uuid4
from Weddingram.settings import MEDIA_ROOT


def about(request):
    return render(request, 'Weddingram/about.html')

def copyright(request):
    return render(request, 'Weddingram/copyright.html')

def account(request):
    return render(request, 'Weddingram/account.html')

def weddingvows(request):
    return render(request, 'Weddingram/weddingvows.html')

def profile(request):
    return render(request, 'Weddingram/profile.html')

def location(request):
    return render(request, 'Weddingram/location.html')

def index(request):
    return render(request, 'Weddingram/index.html')

class Main(APIView):
    def get(self, request):
        feed_object_list = Feed.objects.all().order_by('-id')
        feed_list = []

        for feed in feed_object_list:
            reply_objects_list = Reply.objects.filter(feed_id=feed.id)
            reply_list = []
            for reply in reply_objects_list:
                reply_list.append(dict(feed_id=reply.feed_id,
                                       comment=reply.comment,
                                       writer_id=reply.writer_id
                                       ))
            feed_list.append(dict(id=feed.id,
                                  image=feed.image,
                                  content=feed.content,
                                  tag=feed.tag,
                                  write_date=feed.write_date,
                                  reply_list=reply_objects_list
                                  ))

        return render(request, 'Weddingram/main.html', context=dict(feed_list=feed_list))


class UploadFeed(APIView):
    def post(self, request):
        file = request.FILES['file']
        uuid_name = uuid4().hex
        save_path = os.path.join(MEDIA_ROOT, uuid_name)
        with open(save_path, 'wb+') as destination:
            for chunk in file.chunks():
                destination.write(chunk)
                content = request.data.get('content')
                image = uuid_name
                tag = request.data.get('tag')

        Feed.objects.create(content=content,
                            image=image,
                            like_count=0,
                            tag=tag)

        return Response(status=200)


class UploadReply(APIView):
    def post(self, request):
        feed_id = request.data.get('feed_id', None)
        writer_id = request.data.get('writer_id', None)
        comment = request.data.get('comment', None)

        Reply.objects.create(feed_id=feed_id, writer_id=writer_id, comment=comment)

        return Response(status=200)

templates/Weddingram/account.html
{% extends './base.html' %}
{% load static %}

{% block title %}
    Weddingram
{% endblock title %}

{% block search-block %}
<div class="search-guide">
  <span class="search-icon"></span>
  <input type="text" class="search-placeholder" value="검색" onfocus="if (this.value == '검색') {this.value = '';}" onblur="if (this.value == '') {this.value = '검색';}">
</div>
{% endblock search-block %}

{% block homemenu %}
<!--a href="/main/"><img src="{% static 'images/svg/home.svg' %}" id="ad_fd" class="postc" alt=""></a-->
{% endblock homemenu %}

{% block main-block %}
    <main>
      <div class="main-sub">
        <header>
          <div class="header-grid">
            <div class="profile-pic">
              <img src="{% static './images/weddingram_profile.png' %}" />
            </div>
            <div class="profile-info">
              <div class="title">
                <h2>Weddingram</h2>
                <span class="verified-icon"></span>
                <button class="primary">verified</button>
              </div>
              <div class="desktop-only">
                <div class="details">
                  <ul>
                    <li>게시물 <span>42</span></li>
                    <li class="openPopupFollower">팔로워 <span>6.11m</span></li>
                    <li class="openPopupFollow">팔로우 <span>2</span></li>
                  </ul>
                </div>
                <div class="description row last">
                    <h1>WEDDINGRAM 🤵👰‍♀️</h1>
                  <span>
                    🗓️ 2022년 6월 11일, 🕛 12시 정각<br>
                    📌 의정부 서계종택 <a href="http://naver.me/GfaMZNkI" class="pd" target="_blank">naver.me/GfaMZNkI</a>
                  </span>
                  <div class="pds"><a href="https://www.instagram.com/marcngine/" target="_blank" style="color: #000;font-weight:500;">marcngine</a>님과
                     <a href="https://www.instagram.com/_your_jane/" target="_blank" style="color: #000;font-weight:500;">_your_jane</a>님이 팔로우합니다.</div>
                </div>
                </div>
              </div>
            </div>
          </div>
          <!-- 프로필 설명 영역 모바일 화면 -->
          <div class="profile-info mobile-only">
            <div class="description row">
              <h1>WEDDINGRAM 🤵👰‍♀️</h1>
                  <span>
                    🗓️ 2022년 6월 11일, 🕛 12시 정각<br>
                    📌 의정부 서계종택 <a href="http://naver.me/GfaMZNkI" class="pd" target="_blank">naver.me/GfaMZNkI</a>
                  </span>
                  <div class="pds"><a href="https://www.instagram.com/marcngine/" target="_blank" style="color: #000;font-weight:500;">marcngine</a>님과
                     <a href="https://www.instagram.com/_your_jane/" target="_blank" style="color: #000;font-weight:500;">_your_jane</a>님이 팔로우합니다.</div>
                </div>
            </div>
          </div>
        </header>

        <!-- 프로필 갤러리 -->
        <div class="b_contents">
            <h1>계좌안내</h1>
            <dl>
                <dt>신랑 측</dt>
                    <dd><br>문창연 : <span>국민은행 : 754210450238</span><br>
                            문상우(혼주) : <span>대구은행 : 074080252034</span><br><br></dd>

                <dt>신부 측</dt>
                    <dd><br>송제희 : <span>국민은행 : 91033546776</span></dd>

            </dl>
        </div>

        <!-- 푸터 영역 -->
        <div class="p-footer">
          <footer>
            {% endblock main-block %}
            {% block footer %}
          </footer>
        </div>

      </div>
    </main>
    {% endblock footer %}

templates/Weddingram/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <meta name="description" content="웨딩그램, 프로포즈 사이트">
        <!-- 공유 시 OG이미지 사용을 위한 태그 모음 -->
        <meta property="og:type" content="website"> <!-- 공통 -->
        <meta property="og:url" content="https://www.weddingram.kr"> <!-- 공통 -->
        <meta property="og:title" content="웨딩그램(Weddingram)"> <!-- 공통 -->
        <meta property="og:image" content="https://www.weddingram.kr/static/images/ogimage_normal.png"> <!-- 공통 | 절대값으로 입력 -->
        <meta property="og:description" content="문창연, 송제희의 웨딩그램, 청첩장, 식장위치, 결혼날짜, 결혼식 장소"> <!-- 공통 -->
        <meta property="og:site_name" content="웨딩그램">
        <meta property="og:locale" content="utf-8">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <meta name="twitter:card" content="summary" /> <!-- 트위터 -->
        <meta name="twitter:title" content="웨딩그램(Weddingram)" /> <!-- 트위터 -->
        <meta name="twitter:description" content="문창연, 송제희의 웨딩그램, 청첩장, 식장위치, 결혼날짜, 결혼식 장소" /> <!-- 트위터 -->
        <meta name="twitter:image" content="https://www.weddingram.kr/static/images/ogimage_normal.png" /> <!-- 트위터 -->
        <meta name="twitter:site" content="@2dayer" />  <!-- 트위터 -->
        <meta name="twitter:creator" content="@2dayer" /> <!-- 트위터 -->
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
        <!-- 스크립트 -->
        <script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>
        <script src="{% static 'js/script.js' %}"></script>
        <!-- JQuery - 드래그 드롭 설정-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <!-- 카카오톡 연결 -->
        <script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-2FE8PWJBQQ"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-2FE8PWJBQQ');
        </script>
        <!-- 네이버 검색 등록 -->
    </head>
    <body>
        <!-- 상단 네비게이션 -->
        <nav>
        <div class="fixed">
            <div class="nav-content">
            <a href="/main/"><img src="{% static 'images/weddingram-logo.png' %}" class="logo" style="image-rendering: -webkit-optimize-contrast;" alt=""/></a>
            <div class="desktop-only">
                {% block search-block %}
                {% endblock search-block %}
            </div>
            <div class="nav-items">
                {% block homemenu %}
                {% endblock homemenu %}
                <a href="http://kko.to/fvqgBk7gK"><img src="{% static 'images/svg/liked.svg' %}" class="likes" alt=""></a>
                <a href="{% url 'content:location' %}" title="찾아오시는 길"><img src="{% static 'images/svg/explore.svg' %}" class="explore" alt=""></a>
                <a href="{% url 'content:profile' %}"><img src="{% static 'images/weddingram_profile.png' %}" class="user-profile" style="image-rendering: -webkit-optimize-contrast;" alt=""></a>
            </div>
            </div>
        </div>
        <div class="mock"></div>
        </nav>
        <!-- 상단 네비게이션 끝 -->
        {% block main-block %}
        {% endblock main-block %}
                <p>
                    <a href="{% url 'content:about' %}" class="fa" title="웨딩그램에 대하여">소개</a> ∙
                    <a href="{% url 'content:weddingvows' %}" class="fa" title="혼인서약서">약관</a> ∙
                    <a href="https://naver.me/GfaMZNkI" class="fa" target="_blank" title="식장 지도">맵</a> ∙
                    <a href="{% url 'content:copyright' %}" class="fa" title="저작권">저작권</a> ∙
                    <a href="https://www.youtube.com/channel/UC5lqMuY2QALPu4xWKJnFHjQ" class="fa" target="_blank" title="유튜브 바로가기">유튜브</a> ∙
                    <a href="https://www.craft.do/s/R2uIvu6KMRQNXj" class="fa" target="_blank" title="업데이트 로그">업데이트</a>
                    <br><br>
                    <strong>© 2022 WEDDINGRAM FROM MARC</strong>
                </p>

        {% block footer %}
        {% endblock footer %}

        {% block modal-block %}
        {% endblock modal-block %}

        {% block script-block %}
        {% endblock script-block %}

        <!-- 팔로워 팝업 -->
        <div id="popupfr">
            <div id="popup-f">
                <div class="header-f">
                    <div class="leftf"></div>
                    <div class="centerf"><h2>팔로워</h2></div>
                    <div class="rightf"><img src="{% static 'images/svg/close.svg' %}" class="close"></div>
                </div>
                <div class="mpop-fr">
                    <span>🤵👰‍♀️</span><br>축하해 주신 분들 모두가 팔로워입니다.<br>앞으로 함께 걸어갈 저희 커플을 계속 팔로우해주세요 :)
                </div>
            </div>
        </div>

        <!-- 팔로우 팝업 -->
        <div id="popupf">
            <div id="popup-f">
                <div class="header-f">
                    <div class="leftf"></div>
                    <div class="centerf"><h2>팔로우</h2></div>
                    <div class="rightf"><img src="{% static 'images/svg/close.svg' %}" class="close"></div>
                </div>
                <div class="mpop-f">
                    <div>
                        <div class="profile-card">
                            <div class="image2">
                                <img src="{% static 'images/marcngine.jpg' %}" title="marcngine님의 프로필사진">
                            </div>
                            <div class="center2">
                                <p class="username">marcngine</p>
                                <p class="sub-text2">Marc</p>
                            </div>
                            <div class="right"><button class="action-btn"><a href="https://www.instagram.com/marcngine/" target="_blank">방문</a></button></div>
                         </div>
                    </div>
                    <div>
                        <div class="profile-card">
                            <div class="image2">
                                <img src="{% static 'images/your_jane.jpeg' %}" title="_your_jane님의 프로필사진">
                            </div>
                            <div class="center2">
                                <p class="username">_your_jane</p>
                                <p class="sub-text2">희</p>
                            </div>
                            <div class="right"><button class="action-btn"><a href="https://www.instagram.com/_your_jane/" target="_blank">방문</a></button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 팔로우팝업 끝 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

templates/Weddingram/copyright.html
{% extends './base.html' %}
{% load static %}

{% block title %}
    Weddingram
{% endblock title %}

{% block search-block %}
<div class="search-guide">
  <span class="search-icon"></span>
  <input type="text" class="search-placeholder" value="검색" onfocus="if (this.value == '검색') {this.value = '';}" onblur="if (this.value == '') {this.value = '검색';}">
</div>
{% endblock search-block %}

{% block homemenu %}
<!--a href="/main/"><img src="{% static 'images/svg/home.svg' %}" id="ad_fd" class="postc" alt=""></a-->
{% endblock homemenu %}

{% block main-block %}
    <main>
      <div class="main-sub">
        <header>
          <div class="header-grid">
            <div class="profile-pic">
              <img src="{% static './images/weddingram_profile.png' %}" />
            </div>
            <div class="profile-info">
              <div class="title">
                <h2>Weddingram</h2>
                <span class="verified-icon"></span>
                <button class="primary">verified</button>
              </div>
              <div class="desktop-only">
                <div class="details">
                  <ul>
                    <li>게시물 <span>42</span></li>
                    <li class="openPopupFollower">팔로워 <span>6.11m</span></li>
                    <li class="openPopupFollow">팔로우 <span>2</span></li>
                  </ul>
                </div>
                <div class="description row last">
                  <h1>WEDDINGRAM 🤵👰‍♀️</h1>
                  <span>
                    🗓️ 2022년 6월 11일, 🕛 12시 정각<br>
                    📌 의정부 서계종택 <a href="http://naver.me/GfaMZNkI" class="pd" target="_blank">naver.me/GfaMZNkI</a>
                  </span>
                  <div class="pds"><a href="https://www.instagram.com/marcngine/" target="_blank" style="color: #000;font-weight:500;">marcngine</a>님과
                     <a href="https://www.instagram.com/_your_jane/" target="_blank" style="color: #000;font-weight:500;">_your_jane</a>님이 팔로우합니다.</div>
                </div>
                </div>
              </div>
            </div>
          </div>
          <!-- 프로필 설명 영역 모바일 화면 -->
          <div class="profile-info mobile-only">
            <div class="description row">
                <h1>WEDDINGRAM 🤵👰‍♀️</h1>
                  <span>
                    🗓️ 2022년 6월 11일, 🕛 12시 정각<br>
                    📌 의정부 서계종택 <a href="http://naver.me/GfaMZNkI" class="pd" target="_blank">naver.me/GfaMZNkI</a>
                  </span>
                  <div class="pds"><a href="https://www.instagram.com/marcngine/" target="_blank" style="color: #000;font-weight:500;">marcngine</a>님과
                     <a href="https://www.instagram.com/_your_jane/" target="_blank" style="color: #000;font-weight:500;">_your_jane</a>님이 팔로우합니다.</div>
                </div>
            </div>
          </div>
        </header>

        <!-- 프로필 갤러리 -->
        <div class="b_contents">
            <h1>저작권 정보</h1>
            <dl>
                <!-- 영상음악 -->
                <dt>음악</dt>
                    <dd><br>
                        <span>이루마의 곡의 경우 <a href="https://www.findcopyright.or.kr/" target="_blank">저작권비즈니스지원센터</a>를 통해 정식으로 계약하였습니다.</span><br><br></dd>

                    <dd><span>Ennio Morricone - Love Affair(End Title), Love Affair OST</span></dd>
                    <dd>
                      <p style="margin:5px 15px;">프로포즈 영상에 쓰인 곡은 Ennio morricone 가 작곡한 곡으로
                          워렌 비티와 아네트 베닝이 주연을 맡았던 1994년작 <span>러브 어페어(Love Affair) OST</span> 앨범의 마지막곡이자,
                          영화명과 동일한 제목을 가진 <span>Love Affair(End Credit)</span>입니다.<br>
                        진짜 이 앨범은 버릴 곡 하나 없는 앨범이라 너무나 애정하는 앨범이에요.<br>

                          사실 영상의 메인 테마 곡으로 이루마의 'Destiny of Love'와 엄청나게 고민했어요.
                        'Destiny of Love'는 오랜동안 우리 이야기를 표현한 곡 같다고 생각하던 곡이라서요.

                        다만 영상을 처음 만들어야겠다고 생각했을 때부터 제 머리 속에서 그린 시나리오가 이 곡을 전제로 하기도 했고,
                          잔잔하게 흘러가다가 2분이 지난 즈음부터 클라이막스가 전개되는 곡의 특성상 제가 생각한 영상의 흐름과 잘 어울린다고 생각해서
                          결국은 이 곡을 영상의 메인 테마곡으로 삼았습니다.<br><br>

                          <strong>이 곡의 정식 사용권을 얻고 싶어서 국내 저작권 관련 사이트를 다 확인했는데, 이상하게도 없더라구요.
                          Warner Music Group(WMG)에 저작권이 있다는 걸 확인하고 짧은 영어로 몇 번이나 메일을 보냈는데 씹혔습니다 ㅠㅠ
                          결국 유투브에 올라간 영상은 구매하지 못했네요.<br>나중에라도 구매하게 되면 업데이트 하겠습니다.</strong><br>

                      </p>
                    <br><br>
                    </dd>
                    <dd><span>Yiruma - Destiny of Love</span></dd>
                    <dd>
                      <p style="margin:5px 15px;">위에도 적었지만 <span>저희 커플의 테마곡</span>이라고 생각하는 곡이에요.<br>
                        아쉽게도 영상에는 쓰이지 못했지만 대신 웹사이트 배경음악으로 대신 선택했습니다.
                        이루마 곡들 중에선 'Kiss the rain'이나 'Chaconne' 같은 곡들이 상대적으로 더 유명하지만 개인적으론 처음 들었을 때부터 가장 좋아했던 이루마의 곡이었습니다.<br>
                        <font style="color: #CCCCCC">한국음악저작권협회필 / 계약번호: 202204261 / [전송권]홈페이지배경음악(BGM)</font></p>
                    <br><br>
                    </dd>
                    <!-- 해외음악 -->
                <dt>해외음악</dt>
                    <dd><br><span><a href="https://spitz-web.com" class="pd" target="_blank">Spitz</a>의 소속사 글라스호퍼의 법무부에 확인하였고, 개인사용 범위로 간주되어 사용해도 괜찮다는 회신을 받았습니다.</span><br>
                        <figure style="text-align: center;">
                        <img src="{% static 'images/spitz.png' %}" style="height:300px;margin-top:10px;">
                        <figcaption style="color:rgba(200, 200, 200);font-size:11px;text-align: center;">글라스호퍼 법무팀에서도 문제없다고!</figcaption>
                      </figure>
                        <br></dd>
                    <dd><span>Spitz - 君が思い出になる前に</span></dd>
                    <dd>
                        <p style="margin:5px 15px;">제작후기 영상에 쓰인 Spitz의 1993년 곡입니다. 
                        <span>'당신이 추억이 되기 전에'</span> 라는 타이틀이 프로포즈와 어울리진 않지만 개인적으로 오랜동안 좋아했던 곡이고, Spitz 곡 중에서도 제일 좋아하는 곡이라 꼭 어디엔가는 쓰고 싶었어요.</p>
                    <br><br></dd>
                    <!-- 폰트 -->
                  <dt>폰트</dt>
                    <dd><br><span>Weddingram 로고에 쓰인 폰트는 Grandista 폰트로 <a href="https://www.myfonts.com" target="_blank" class="pd">myfonts.com</a>에서 정식으로 구매하였습니다.<br>
                        기타 이미지나 영상에 쓰인 폰트들은 대부분 시스템 기본 폰트나 구글이나 네이버에서 제공하는 무료 서체들이구요, 캘리그래피는 직접 그린 이미지입니다.</span><br><br></dd>
                    <dd><span>Grandista</span></dd>
                    <dd>
                        <p style="margin:5px 15px;">인스타그램 로고 서체로 검색해보면 대부분 기존 로고<font class="grey">(2013년 이전)</font>는 <span>Billabong</span>에 가깝고, 최신 로고는 <span>Blue Vinyl</span> 과 유사하다고 알려줍니다<font class="grey">(해외 사이트에서도)</font>
                        그런데 제가 보기엔 영어 소문자 <span>r</span> 이나 <span>i</span>의 쉐이프가 아무리 봐도 둘 다 아닌 것 같아서 고민 중이었는데 외국의 한 커뮤니티에서 'Grandista'라는 폰트가 비슷하다는 글을 보고 테스트해보니 이게 제일 비슷한 것 같더라구요.</p>
                    <br>
                    <figure style="text-align: center;">
                      <img src="{% static 'images/gallery/font_style.png' %}" style="height:250px;" title="서체 비교">
                      <figcaption style="color:rgba(200, 200, 200);font-size:11px;text-align: center;">서체비교</figcaption>
                    </figure>
                    <br>
                    </dd>
                    </dd>
                    
            </dl>
        </div>

        <!-- 푸터 영역 -->
        <div class="p-footer">
          <footer>
            {% endblock main-block %}
            {% block footer %}
          </footer>
        </div>

      </div>
    </main>
    {% endblock footer %}

templates/Weddingram/naver5b3a1ce57d4d58a4787c6e9e9facf286.html
naver-site-verification: naver5b3a1ce57d4d58a4787c6e9e9facf286.html